backend/api/auth.go, backend/api/model/auth.go, backend/api/model/tweet.go, backend/api/model/user.go, backend/api/tweet.go, backend/services/services.go
=> Use gin.context.bind

.travis.yml, README.md, circle.yml, frontend/config/webpack.test.js, frontend/src/app/app.module.ts
=> [WIP] Add continuous integration

frontend/src/app/app.module.ts, frontend/src/app/components/home.component.ts, frontend/src/app/components/index.ts, frontend/src/app/components/login.component.ts, frontend/src/app/components/singup.component.ts, frontend/src/app/components/tweet/tweet.component.html, frontend/src/app/components/tweet/tweet.component.scss, frontend/src/app/components/tweet/tweet.component.ts, frontend/src/app/me/me.component.ts, frontend/src/app/me/me.module.ts, frontend/src/app/me/tweets.component.ts, frontend/src/app/shared/index.ts, frontend/src/app/shared/tweet.model.ts, frontend/src/app/shared/tweet.service.ts
=> Add tweet component

frontend/src/app/app.module.ts, frontend/src/app/components/home.component.ts, frontend/src/app/components/index.ts, frontend/src/app/components/tweet/index.ts, frontend/src/app/components/tweet/tweets.component.ts, frontend/src/app/components/tweet/tweets.module.ts, frontend/src/app/me/index.ts, frontend/src/app/me/me.module.ts, frontend/src/app/me/my-tweets.component.ts
=> Refactor `TweetsComponent`

backend/api.yaml, backend/main.go
Make authentication required for all endpoints other than login and singup.
Also rename register->signup
closes #40
=> Make all endpoints require authentication

backend/api.yaml, backend/api/model/tweet.go, backend/api/model/user.go, backend/database/model/tweet.go, backend/database/tweet.go, backend/services/services.go
For now Liked and Retweeted fileds in Tweet and following field in User are always false. This functionality will be added in next sprint when we implement NoSQL database that will store this data.
closes #41 
closes #44
=> Update db and api models

backend/api.yaml, backend/api/auth.go, backend/api/model/auth.go, backend/services/services.go
=> Return data of the user that logs in

backend/main.go, backend/middleware/content_type_checker.go
I didn't find any such middleware so I decided to wrtie my own. Its simple and does not do a lot, but it will be easy to extend it so that you can set which content types to accept.
closes #48
=> Add content type checking middleware

backend/main.go
Documentation of official CORS middleware: https://github.com/gin-contrib/cors
closes #54
=> Add basic CORS support

backend/main.go, backend/services/services.go
=> Fix home feed endpoint

frontend/src/app/app.component.ts, frontend/src/app/app.module.ts, frontend/src/app/components/home.component.ts, frontend/src/app/components/index.ts, frontend/src/app/components/login.component.ts, frontend/src/app/components/logout.component.ts, frontend/src/app/components/signup.component.ts, frontend/src/app/components/tweet/create-tweet.component.html, frontend/src/app/components/tweet/create-tweet.component.ts, frontend/src/app/layout/navigation-bar.component.ts, frontend/src/app/me/me.module.ts, frontend/src/app/me/my-tweets.component.ts, frontend/src/app/shared/api.service.ts, frontend/src/app/shared/auth.service.ts, frontend/src/app/shared/index.ts, frontend/src/app/shared/store-helper.ts, frontend/src/app/shared/tweet.model.ts, frontend/src/app/shared/user.model.ts, frontend/src/app/shared/user.service.ts, frontend/src/app/store.ts
=> Add services

frontend/src/app/components/index.ts, frontend/src/app/components/login.component.html, frontend/src/app/components/login.component.scss, frontend/src/app/components/login.component.ts, frontend/src/app/components/signup.component.html, frontend/src/app/components/signup.component.scss, frontend/src/app/components/signup.component.ts, frontend/src/app/components/tweet/create-tweet.component.html, frontend/src/app/components/tweet/create-tweet.component.scss, frontend/src/app/components/tweet/create-tweet.component.ts, frontend/src/app/components/tweet/index.ts, frontend/src/app/components/tweet/tweets.component.scss, frontend/src/app/components/tweet/tweets.component.ts, frontend/src/app/components/tweet/tweets.module.ts, frontend/src/app/layout/navigation-bar.component.ts, frontend/src/app/me/me.component.html, frontend/src/app/me/me.component.scss, frontend/src/app/me/me.component.ts, frontend/src/app/me/my-tweets.component.ts, frontend/src/app/shared/auth.service.ts, frontend/src/app/shared/tweet.model.ts, frontend/src/app/shared/tweet.service.ts, frontend/src/app/shared/user.service.ts, frontend/src/app/store.ts, frontend/src/index.html
closes #62 
closes #65 
closes #28
=> Add tweet creation mechanism

backend/api.yaml, backend/api/auth.go, backend/api/model/auth.go, backend/api/model/tweet.go, backend/api/tweet.go, backend/main.go, backend/middleware/token_authenticator.go, backend/services/services.go
Few minor fixes.
Also closes #73
=> Minor fixes

backend/api/api.go, backend/api/auth.go, backend/api/model/auth.go, backend/api/tweet.go, backend/api/user.go, backend/config/config.go, backend/database/database_connection.go, backend/database/model/tweet.go, backend/database/model/user.go, backend/database/tweet.go, backend/database/user.go, backend/main.go, backend/middleware/token_authenticator.go, backend/server/setup.go, backend/service/service.go, backend/service/utils.go, backend/services/services.go, postgres/schema.sql
This is just the beginning of the work, I'm working on refactoring the code and on proper desing of the app. I'll be adding new commits when I get more things done.
Most likely:
closes #26
closes #77 
closes #81 
closes #85
TODO:
=> Refactor backend code

backend/database/user.go, backend/service/service.go
=> Update user last login time

backend/database/errors.go, backend/database/tweet.go, backend/database/user.go, backend/server/setup.go, backend/service/errors.go, backend/service/service.go
=> Improve error handling

backend/api/api.go, backend/api/provider.go, backend/database/accessor.go, backend/database/database.go, backend/database/tweet.go, backend/database/user.go, backend/server/setup.go, backend/service/provider.go, backend/service/service.go
=> improve package layout

backend/service/converters/tweet.go, backend/service/converters/tweetconverter_test.go, backend/service/converters/user.go, backend/service/converters/userconverter_test.go, backend/service/service.go
=> Add converters tests

.travis.yml, backend/middleware/content_type_checker_test.go, backend/middleware/error_handler.go, backend/middleware/error_handler_test.go, backend/middleware/token_authenticator.go, backend/middleware/token_authenticator_test.go
I think we can merge this now and when I find solution to #117 I will create another PR.
solves #105
=> Add middleware tests

README.md, docker/backend.yml, docker/core.yml, docker/frontend.yml, docker/production.yml, postgres/Dockerfile, postgres/fixtures.sql, postgres/init.sh, postgres/schema.sql
- remove MongoDB
- separate schema and fixtures to different files
- add NoSQL values to PostgreSQL (`likes` and `retweets` in `tweet` table)
closes #125
=> Database cleanup

backend/api/tweet.go, backend/tests/integration/server_test.go, backend/tests/integration/test_helpers.go
=> Add support for getting tweets of user with given ID

.travis.yml, backend/api/provider.go, backend/api/tweet.go, backend/database/accessor.go, backend/database/tweet.go, backend/model/tweet.go, backend/server/setup.go, backend/service/provider.go, backend/service/service.go, backend/tests/integration/server_test.go, backend/tests/integration/test_helpers.go, postgres/schema.sql
=> Implement liking tweets

backend/api/provider.go, backend/api/user.go, backend/database/accessor.go, backend/database/user.go, backend/server/setup.go, backend/service/provider.go, backend/service/service.go, backend/tests/integration/server_test.go, backend/tests/integration/test_helpers.go, postgres/schema.sql
=> Implement following users

.travis.yml, backend/cache/cache.go, backend/cache/dummy.go, backend/cache/dummy_test.go, backend/cache/provider.go, backend/cache/redis.go, backend/cache/redis_test.go, backend/config.yaml, backend/config/config.go, backend/database/database.go, backend/database/tweet.go, backend/database/user.go, backend/main.go, backend/server/setup.go, backend/test.yaml, backend/tests/integration/test_helpers.go, docker/test.yml
=> Add Redis cache

backend/api/provider.go, backend/api/user.go, backend/database/accessor.go, backend/database/user.go, backend/model/user.go, backend/server/setup.go, backend/service/provider.go, backend/service/service.go, backend/tests/integration/server_test.go
=> Add followees and followers of user endpoints

.travis.yml, backend/api/provider.go, backend/api/user.go, backend/server/setup.go, backend/tests/integration/server_test.go, backend/tests/integration/test_helpers.go, docker/test.yml
=> Refactor server tests

.travis.yml, backend/Makefile, backend/tests/integration/test_helpers.go, docker/test.yml
=> add simple makefile

README.md, backend/Makefile
fixes #158 
fixes #157
fixes #156
fixes #155
=> improve makefile and update readme

backend/cache/cache_suite_test.go, backend/cache/dummy_test.go, backend/cache/redis_test.go, backend/middleware/content_type_checker_test.go, backend/middleware/error_handler_test.go, backend/middleware/middleware_suite_test.go, backend/middleware/token_authenticator_test.go, backend/server/setup.go, backend/tests/integration/server_test.go, backend/tests/integration/test_helpers.go, postgres/schema.sql
=> Introduce TDD tests

backend/cache/redis.go, backend/cache/redis_test.go, backend/config.yaml, backend/config/config.go, backend/config/interfaces.go, backend/database/database.go, backend/main.go, backend/server/setup.go, backend/test.yaml, backend/test_config.yaml, backend/tests/integration/server_test.go
=> read postgres and redis ports from config file

frontend/src/app/app.module.ts, frontend/src/app/components/index.ts, frontend/src/app/components/tweet/index.ts, frontend/src/app/components/tweet/tweet.component.html, frontend/src/app/components/tweet/tweet.component.scss, frontend/src/app/components/tweet/tweet.component.ts, frontend/src/app/components/user/index.ts, frontend/src/app/components/user/user.component.html, frontend/src/app/components/user/user.component.scss, frontend/src/app/components/user/user.component.ts, frontend/src/app/components/user/users.component.scss, frontend/src/app/components/user/users.component.ts, frontend/src/app/components/user/users.module.ts, frontend/src/app/layout/navigation-bar.component.scss, frontend/src/app/layout/navigation-bar.component.ts, frontend/src/app/me/followers.component.ts, frontend/src/app/me/following.component.ts, frontend/src/app/me/me.component.ts, frontend/src/app/me/me.module.ts, frontend/src/app/shared/api.service.ts, frontend/src/app/shared/tweet.service.ts, frontend/src/app/shared/user.model.ts, frontend/src/app/shared/user.service.ts, frontend/src/app/store.ts
This PR adds some basic functionalities connected with following user to frontend.
Fixes and rest of feature will be added when there will be implemented search function.
=> Add following functionalities to frontend

backend/api.yaml, backend/fulltextsearch/fulltextsearch.go, backend/main.go, docker/backend.yml, docker/core.yml, docker/production.yml
=> add logstash to core docker, update api.yaml

frontend/src/app/app.module.ts, frontend/src/app/components/search.component.html, frontend/src/app/components/search.component.scss, frontend/src/app/components/search.component.ts, frontend/src/app/components/tweet/tweet.component.html, frontend/src/app/components/tweet/tweet.component.ts, frontend/src/app/components/user/user.component.html, frontend/src/app/components/user/user.component.scss, frontend/src/app/components/user/user.component.ts, frontend/src/app/components/user/users.component.scss, frontend/src/app/me/me.component.ts, frontend/src/app/shared/index.ts, frontend/src/app/shared/search.service.ts, frontend/src/app/store.ts
=> Add search to frontend

frontend/src/app/components/home.component.ts, frontend/src/app/components/login.component.ts, frontend/src/app/components/search.component.html, frontend/src/app/components/search.component.ts, frontend/src/app/components/tweet/tweet.component.html, frontend/src/app/components/tweet/tweet.component.ts, frontend/src/app/components/tweet/tweets.component.ts, frontend/src/app/components/user/user.component.html, frontend/src/app/components/user/user.component.ts, frontend/src/app/components/user/users.component.ts, frontend/src/app/me/me.component.ts, frontend/src/app/me/me.module.ts, frontend/src/app/shared/auth.service.ts, frontend/src/app/shared/search.service.ts, frontend/src/app/shared/tweet.model.ts
=> Add number of likes; Fix following in search;

frontend/src/app/me/me.component.html, frontend/src/app/me/me.component.ts
=> Fix counters on reload

backend/api.yaml, backend/api/provider.go, backend/api/tweet.go, backend/api/user.go, backend/database/tweet.go, backend/server/setup.go, backend/service/provider.go, backend/service/service.go, backend/service/utils.go, backend/storage/accessor.go, backend/storage/tweet.go, backend/storage/user.go, backend/tests/integration/server_test.go, backend/tests/integration/test_helpers.go, backend/utils/tweets.go
=> Add users feed

backend/api.yaml, backend/api/provider.go, backend/api/tweet.go, backend/api/user.go, backend/server/setup.go, backend/storage/tweet.go, backend/storage/user.go, backend/tests/integration/server_test.go, backend/tests/integration/test_helpers.go
=> Fix panic and move users tweets endpoint

frontend/package.json, frontend/src/app/components/home.component.html, frontend/src/app/components/home.component.scss, frontend/src/app/components/home.component.ts, frontend/src/app/components/tweet/create-tweet.component.html, frontend/src/app/components/tweet/create-tweet.component.scss, frontend/src/app/components/tweet/tweet.component.html, frontend/src/app/components/tweet/tweet.component.ts, frontend/src/app/components/user/user.component.ts, frontend/src/app/layout/navigation-bar.component.ts, frontend/src/app/me/followers.component.ts, frontend/src/app/me/following.component.ts, frontend/src/app/me/me.component.ts, frontend/src/app/me/my-tweets.component.ts, frontend/src/app/shared/api.service.ts, frontend/src/app/shared/user.service.ts, frontend/src/app/store.ts
=> Change landing page; Change fixed 2m tweet time difference

nginx/conf.d/chirp.conf
=> add cache to nginx

backend/config.yaml, backend/config/config.go, backend/config/interfaces.go, backend/docker_config.yaml, backend/main.go, backend/password/bcrypt.go, backend/password/interface.go, backend/password/utils.go, backend/server/setup.go, backend/service/service.go, backend/test_config.yaml, backend/tests/integration/server_test.go, postgres/fixtures.sql
=> Add password hashing using bcrypt
